[package]
name = "rustci-vm-ci"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rust 镜像 jdk.vm.ci（JVMCI→RustCI）；第一期核心接口子集"

[dependencies]
rustci-collections = { path = "../rustci-collections" }

[lib]
name = "rustci_vm_ci"
path = "src/lib.rs"
# 子模块（src/ 下目录）：meta/ code/ runtime/ hotspot/ services/
